// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9c5sO2dXuJCWZDcrx01JNLb74unEDZE',
    appId: '1:917388909881:web:171866169826d4c337dce8',
    messagingSenderId: '917388909881',
    projectId: 'gestion-ahorros',
    authDomain: 'gestion-ahorros.firebaseapp.com',
    storageBucket: 'gestion-ahorros.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3KTPY2D435KmPgy0x1Uczq7PY9PiarM',
    appId: '1:917388909881:android:0535c67d007f767837dce8',
    messagingSenderId: '917388909881',
    projectId: 'gestion-ahorros',
    storageBucket: 'gestion-ahorros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj6noMp8aHnmLxFfs3_9iI51MsfpAfcMM',
    appId: '1:917388909881:ios:e86691f395c16b4637dce8',
    messagingSenderId: '917388909881',
    projectId: 'gestion-ahorros',
    storageBucket: 'gestion-ahorros.firebasestorage.app',
    iosBundleId: 'com.example.gestionAhorros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj6noMp8aHnmLxFfs3_9iI51MsfpAfcMM',
    appId: '1:917388909881:ios:e86691f395c16b4637dce8',
    messagingSenderId: '917388909881',
    projectId: 'gestion-ahorros',
    storageBucket: 'gestion-ahorros.firebasestorage.app',
    iosBundleId: 'com.example.gestionAhorros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS9c5sO2dXuJCWZDcrx01JNLb74unEDZE',
    appId: '1:917388909881:web:15464fcc4ec3a53637dce8',
    messagingSenderId: '917388909881',
    projectId: 'gestion-ahorros',
    authDomain: 'gestion-ahorros.firebaseapp.com',
    storageBucket: 'gestion-ahorros.firebasestorage.app',
  );
}
